<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'Estitofo_Datamatrix' => $strauss_src . '/tecnickcom/tcpdf/include/barcodes/datamatrix.php',
   'Estitofo_PDF417' => $strauss_src . '/tecnickcom/tcpdf/include/barcodes/pdf417.php',
   'Estitofo_QRcode' => $strauss_src . '/tecnickcom/tcpdf/include/barcodes/qrcode.php',
   'Estitofo_TCPDF_COLORS' => $strauss_src . '/tecnickcom/tcpdf/include/tcpdf_colors.php',
   'Estitofo_TCPDF_FILTERS' => $strauss_src . '/tecnickcom/tcpdf/include/tcpdf_filters.php',
   'Estitofo_TCPDF_FONTS' => $strauss_src . '/tecnickcom/tcpdf/include/tcpdf_fonts.php',
   'Estitofo_TCPDF_FONT_DATA' => $strauss_src . '/tecnickcom/tcpdf/include/tcpdf_font_data.php',
   'Estitofo_TCPDF_IMAGES' => $strauss_src . '/tecnickcom/tcpdf/include/tcpdf_images.php',
   'Estitofo_TCPDF_STATIC' => $strauss_src . '/tecnickcom/tcpdf/include/tcpdf_static.php',
   'Estitofo_TCPDF' => $strauss_src . '/tecnickcom/tcpdf/tcpdf.php',
   'Estitofo_TCPDFBarcode' => $strauss_src . '/tecnickcom/tcpdf/tcpdf_barcodes_1d.php',
   'Estitofo_TCPDF2DBarcode' => $strauss_src . '/tecnickcom/tcpdf/tcpdf_barcodes_2d.php',
);